### ISSUE TITLE
JPEG 2000 license

### ISSUE THREAD

**Issue by RemiSgt** [jai-imageio/jai-imageio-core#15]
First of all, I want to thank you for this great work on the Image IO library. This is a really good idea to create a fork without the JPEG 2000 module.
But I have still one interrogation. From the welcome page, I understand that this project is loaded as a new service through the SPI plugin mechanism of ImageIO. 

Your implementation classes are specified in the META-INF/services directory and loaded thanks to "ImageIO.scanForPlugins();" method.

So, correct me if I am wrong, I need to add in my pom.xml the new dependency jai-imageio-core 1.3.0 and load the project using, for example in a static block, scanForPlugins. But in this case, I still need to keep the old jai_imageio 1.1 dependency to load your new services classes, isn't it ?

Then the jai_imageio 1.1 dependency is still in my application and the JPEG 2000 specific license still apply to my application. So how can I get rid of this license using your library ?

Rémi

**Comment by stain** [comment]
This relates to issue #4 which was resolved - jai-imageio-core does not contain the JPEG 2000 source code, which has been split out to https://github.com/jai-imageio/jai-imageio-jpeg2000 since version 1.2-pre-dr-b04-2014-09-12.

As documented in the [usage](https://github.com/jai-imageio/jai-imageio-core#usage), you should use this dependency:

```xml
<dependency>
    <groupId>com.github.jai-imageio</groupId>
    <artifactId>jai-imageio-core</artifactId>
    <version>1.3.0</version>
</dependency>
```

You should not have jai_imageio 1.1 on the class path at the same time, as that would cause two implementations to be found (`com.github.jaiimageio` is this one, and `com.sun.media.imageio` for the 'classic' jai image IO)

If you are not sure where you are getting jai_imageio 1.1 from, try `mvn dependency:tree` - you can use [Maven excludes](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) if you get this transitively from a third-party dependency.

You should not need any dependency for [javax.imageio.ImageIO](http://docs.oracle.com/javase/7/docs/api/javax/imageio/ImageIO.html), as that is part of the JRE distribution for Java SE.

**Comment by RemiSgt** [comment]
Ok, thanks for the quick reply.

I tried to fully remove the jai_imageio 1.1 dependency and I applied on dcm4che-imageio the exclusion:
```xml
<dependency>
      <groupId>dcm4che</groupId>
      <artifactId>dcm4che-imageio</artifactId>
       <exclusions>
              <exclusion>
                    <groupId>com.sun.media</groupId>
                    <artifactId>jai_imageio</artifactId>
              </exclusion>
       </exclusions>
</dependency>
```

Indeed, the dcm4che-imageio library uses the jai_imageio 1.1 library (it is declared in the pom.xml dependency: http://www.dcm4che.org/maven2/dcm4che/dcm4che-imageio/2.0.25/dcm4che-imageio-2.0.25.pom). This library also provide its own *DicomImageReaderSpi* which extends *ImageReaderSpi*.

The problem is when I tried to retrieve the Dicom ImageReader:
```java
Iterator<ImageReader> iterator = ImageIO.getImageReadersByFormatName("DICOM");
ImageReader reader = iterator.next();
```

I have got the following exception:
```java
java.lang.NoClassDefFoundError: com/sun/media/imageio/stream/StreamSegmentMapper
              at org.dcm4che2.imageioimpl.plugins.dcm.DicomImageReaderSpi.createReaderInstance(DicomImageReaderSpi.java:146)
              at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
              at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:529)
              at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:513)
```

I don’t understand why, the class loader try to reach the *com/sun/media/imageio*, because I exclude all com.sun.media files from the dcm4che-imageio library. A possibility is that the reference of this class is “hard-coded” in the DicomImageReader class, but I found no trace in the source code, see:
-	https://github.com/dicomgrid/dcm4che2/blob/master/dcm4che-imageio/src/main/java/org/dcm4che2/imageioimpl/plugins/dcm/DicomImageReaderSpi.java
-	https://github.com/dicomgrid/dcm4che2/blob/master/dcm4che-imageio/src/main/java/org/dcm4che2/imageioimpl/plugins/dcm/DicomImageReader.java


I know you are not responsible for dcm4chee 2.0.x library, but if you have any ideas please let me know.

**Comment by stain** [comment]
I think it is because of this:

```
stain@biggie:~/src/dcm4che2$ grep -r StreamSegmentMapper .
./dcm4che-imageio/src/main/java/org/dcm4che2/imageio/ItemParser.java:import com.sun.media.imageio.stream.StreamSegmentMapper;
./dcm4che-imageio/src/main/java/org/dcm4che2/imageio/ItemParser.java:public class ItemParser implements StreamSegmentMapper {
```


[ItemParser](https://github.com/dicomgrid/dcm4che2/blob/master/dcm4che-imageio/src/main/java/org/dcm4che2/imageio/ItemParser.java) is used by `DicomImageReader` which is what the  `DicomImageReaderSpi` is trying to instantiate.

But in jai-imageio-core 1.3.0 we renamed `com.sun.media.imageio.stream.StreamSegmentMapper`  to `com.github.jaiimageio.stream.StreamSegmentMapper`  (and the rest of the package).

Perhaps if you use jai-imageio-core version 1.2.1 it should work, that still used the (reserved) `com.sun.media.imageio` package name.

You could also suggest to dcm4che2 if they are able to use jai-imageio-core 1.3.0 instead - they should have similar licensing concerns as JPEG 2000 license is not compatible with their GPL license. (it might or might not be compatible to their dual license MPL)

**Comment by stain** [comment]
Suggested as pull request dicomgrid/dcm4che2#1 - perhaps you want to chase this with their mailing lists or similar, @RemiSgt?

**Comment by RemiSgt** [comment]
Perfect, thank you very much for your help.

It's ok, I subscribed to this thread to receive the notifications from this thread.
