### ISSUE TITLE
invalid version range in java8-and-higher profile

### ISSUE THREAD

**Issue by jameyg42** [jai-imageio/jai-imageio-core#23]
the version range in the java8-and-higher is missing the closing `)`

The invalid range may cause issues with certain versions/implementations of Maven.

see also
https://github.com/google/gson/issues/596
https://github.com/deeplearning4j/dl4j-0.4-examples/issues/76

**Comment by jadrake75** [comment]
+1 after a complete server rebuild and finding the old imageio is not to be found with maven, I came across this github port.... but now the Java 8 issue is blasting me out of the water....

**Comment by Snowynight2011** [comment]
+1 I had the same problem when building it with Maven 2:
"Unable to get dependency information: Unable to read the metadata file for artifact 'com.github.jai-imageio:jai-imageio-core:jar': Invalid JDK version in profile 'java8-and-higher': Unbounded range: [1.8, for project com.github.jai-imageio:jai-imageio-core
com.github.jai-imageio:jai-imageio-core:jar:1.3.1"

The fix is very simple - simply add a closing ) in your pom as below:
<profile>
      <id>java8-and-higher</id>
      <activation>
        <jdk>**[1.8,)**</jdk>
      </activation>

Some of our projects can't be changed to use later Maven versions yet for various reasons. So could you please fix this ASAP?

Many thanks,
Joe

**Comment by atalw** [comment]
Can this please be updated? Somebody has pushed a pull request for this issue as well. I can't update to maven 3 hence the problem.
Thanks!

**Comment by stain** [comment]
Thanks to @butchhoward - sorry for missing this. I will try to make a new release this Easter, meanwhile would any of you care to test the latest `master` as a SNAPSHOT?

**Comment by asraf344** [comment]
@stain : Nice to see the fix. When you are planning to release  1.3.2 ?
Also, I am hoping you have fixed it for "jai-imageio-jpeg2000" as well ?
